
trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '9816b680-f08a-43fe-ac4c-dc5da528dc6a'
  # Web app name
  webAppName: 'WebApp0214'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  # Environment name
  environmentName: 'environment-name'
  # Root folder under which your composer.json file is available.
  rootFolder: $(System.DefaultWorkingDirectory)

stages:
- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(webAppName)
              appType: webApp
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip